services:
  postgres:
    container_name: postgres
    image: postgres:18
    environment:
      POSTGRES_USER: leoga
      POSTGRES_PASSWORD: leoga
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./init-multi-db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
    - backend
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 10
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
    - backend
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - backend
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
      - "19092:19092"
    environment:
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: "1"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LISTENERS: "PLAINTEXT_HOST://:9092,PLAINTEXT://:19092,CONTROLLER://:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT_HOST://localhost:9092,PLAINTEXT://kafka:19092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: "0"
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
      KAFKA_HEAP_OPTS: "-Xms512m -Xmx1024m"
    networks:
      - backend
    volumes:
      - kafka:/var/lib/kafka/data
    healthcheck:
      test: [ "CMD", "bash", "-c", "kafka-topics --bootstrap-server localhost:19092 --list" ]
      interval: 10s
      timeout: 10s
      retries: 10
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.5.6
    command: start-dev
    ports:
      - "8443:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      JAVA_TOOL_OPTIONS: "-Xms512m -Xmx1024m"
#   This works fine on Windows. The following variables may be helpful in other environments (macOS, Linux), just in case.
#      PROXY_ADDRESS_FORWARDING: "true"
#      KEYCLOAK_FRONTEND_URL: "http://localhost:8443"
    networks:
      - backend
    volumes:
      - keycloak-data:/opt/keycloak/data

# GRAFANA
  read:
    image: grafana/loki:latest
    command: "-config.file=/etc/loki/config.yaml -target=read"
    ports:
      - 3101:3100
      - 7946
      - 9095
    volumes:
      - ./logging/loki-config.yaml:/etc/loki/config.yaml
    depends_on:
      - minio
    healthcheck:
      test: [ "CMD", "/usr/bin/loki", "-health" ]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 5
    networks: &loki-dns
      loki:
        aliases:
          - loki

  write:
    image: grafana/loki:latest
    command: "-config.file=/etc/loki/config.yaml -target=write"
    ports:
      - 3102:3100
      - 7946
      - 9095
    volumes:
      - ./logging/loki-config.yaml:/etc/loki/config.yaml
    healthcheck:
      test: [ "CMD", "/usr/bin/loki", "-health" ]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - minio
    networks:
      <<: *loki-dns

  alloy:
    image: grafana/alloy:latest
    volumes:
      - ./logging/alloy-local-config.yaml:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ../../logs:/logs-parent:ro
    command:  run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    ports:
      - 12345:12345
    depends_on:
      - loki-gateway
    networks:
      - loki

  minio:
    image: minio/minio
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /data/loki-data && \
        mkdir -p /data/loki-ruler && \
        minio server /data
    environment:
      - MINIO_ROOT_USER=loki
      - MINIO_ROOT_PASSWORD=supersecret
      - MINIO_PROMETHEUS_AUTH_TYPE=public
      - MINIO_UPDATE=off
    ports:
      - 9000
    volumes:
      - ./.data/minio:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 15s
      timeout: 20s
      retries: 5
    networks:
      - loki

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    depends_on:
      - loki-gateway
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
          - name: Loki
            type: loki
            access: proxy
            url: http://loki-gateway:3100
            jsonData:
              httpHeaderName1: "X-Scope-OrgID"
            secureJsonData:
              httpHeaderValue1: "tenant1"
        EOF
        /run.sh
    ports:
      - "3000:3000"
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana
    networks:
      - loki

  backend:
    image: grafana/loki:latest
    volumes:
      - ./logging/loki-config.yaml:/etc/loki/config.yaml
    ports:
      - "3100"
      - "7946"
    command: "-config.file=/etc/loki/config.yaml -target=backend -legacy-read-mode=false"
    depends_on:
      - loki-gateway
    healthcheck:
      test: [ "CMD", "/usr/bin/loki", "-health" ]
      start_period: 30s
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - loki


  loki-gateway:
    image: nginx:latest
    depends_on:
      - read
      - write
    entrypoint:
      - sh
      - -euc
      - |
        cat <<EOF > /etc/nginx/nginx.conf
        user  nginx;
        worker_processes  5;  ## Default: 1

        events {
          worker_connections   1000;
        }

        http {
          resolver 127.0.0.11;

          server {
            listen             3100;

            location = / {
              return 200 'OK';
              auth_basic off;
            }

            location = /api/prom/push {
              proxy_pass       http://write:3100\$$request_uri;
            }

            location = /api/prom/tail {
              proxy_pass       http://read:3100\$$request_uri;
              proxy_set_header Upgrade \$$http_upgrade;
              proxy_set_header Connection "upgrade";
            }

            location ~ /api/prom/.* {
              proxy_pass       http://read:3100\$$request_uri;
            }

            location = /loki/api/v1/push {
              proxy_pass       http://write:3100\$$request_uri;
            }

            location = /loki/api/v1/tail {
              proxy_pass       http://read:3100\$$request_uri;
              proxy_set_header Upgrade \$$http_upgrade;
              proxy_set_header Connection "upgrade";
            }

            location ~ /loki/api/.* {
              proxy_pass       http://read:3100\$$request_uri;
            }
          }
        }
        EOF
        /docker-entrypoint.sh nginx -g "daemon off;"
    ports:
      - "3100:3100"
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - loki
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411
    networks:
      - loki
      - backend


# JOB-APP SERVICES
  config-server:
    build: ../../configserver #using local Dockerfile inside the project directory
#    image: jobapp/config-server #using spring boot buildpacks plugin
#    image: leogatf/jobapp-config-server #using jib maven plugin
    container_name: config-server
    ports:
      - "8888:8888"
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=/config
      - SPRING_PROFILES_ACTIVE=docker,native #docker,native use this if you want to load local configuration files from the config folder
      - JAVA_TOOL_OPTIONS=-Xms256m -Xmx512m
#      - THC_PATH=/actuator/health # necessary when using buildpacks plugin in order to perform health check
#      - THC_PORT=8889 # necessary when using buildpacks plugin in order to perform health check
    networks:
      - backend
    volumes:
      - ./../../configserver/src/main/resources/config:/config
    healthcheck:
#      test: ["CMD", "/workspace/health-check"] # necessary when using buildpacks plugin in order to perform health check
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"] # if buildpacks plugin is not used, use this test
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
  eureka:
    build: ../../eureka #using local Dockerfile inside the project directory
#    image: jobapp/eureka  #using spring boot buildpacks plugin
#    image: leogatf/jobapp-eureka #using jib maven plugin
    container_name: eureka
    ports:
      - "8761:8761"
    networks:
      - backend
    environment:
      - JAVA_TOOL_OPTIONS=-Xms256m -Xmx512m
      - SPRING_PROFILES_ACTIVE=docker
#      - THC_PATH=/actuator/health # necessary when using buildpacks plugin in order to perform health check
#      - THC_PORT=8761 # necessary when using buildpacks plugin in order to perform health check
    healthcheck:
#      test: ["CMD", "/workspace/health-check"] # necessary when using buildpacks plugin in order to perform health check
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"] # if buildpacks plugin is not used, use this test
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
  gateway:
    build: ../../gateway #using local Dockerfile inside the project directory
#    image: jobapp/gateway  #using spring boot buildpacks plugin
#    image: leogatf/jobapp-gateway #using jib maven plugin
    container_name: gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker,gitdocker
      - JAVA_TOOL_OPTIONS=-Xms256m -Xmx512m
    depends_on:
      config-server:
        condition: service_healthy
      eureka:
        condition: service_healthy
      keycloak:
        condition: service_started
      kafka:
        condition: service_healthy
    networks:
      - backend
  company:
    build: ../../company #using local Dockerfile inside the project directory
#    image: jobapp/company  #using spring boot buildpacks plugin
#    image: leogatf/company #using jib maven plugin
    container_name: company
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker,gitdocker
      - JAVA_TOOL_OPTIONS=-Xms256m -Xmx512m
    depends_on:
      config-server:
        condition: service_healthy
      eureka:
        condition: service_healthy
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - backend
  job:
    build: ../../job #using local Dockerfile inside the project directory
#    image: jobapp/job  #using spring boot buildpacks plugin
#    image: leogatf/job #using jib maven plugin
    container_name: job
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker,gitdocker
      - JAVA_TOOL_OPTIONS=-Xms256m -Xmx512m
    depends_on:
      config-server:
        condition: service_healthy
      eureka:
        condition: service_healthy
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - backend
  review:
    build: ../../review #using local Dockerfile inside the project directory
#    image: jobapp/review #using spring boot buildpacks plugin
#    image: leogatf/review #using jib maven plugin
    container_name: review
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker,gitdocker
      - JAVA_TOOL_OPTIONS=-Xms256m -Xmx512m
    depends_on:
      config-server:
        condition: service_healthy
      eureka:
        condition: service_healthy
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - backend

networks:
  backend:
    driver: bridge
  loki:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  kafka:
  keycloak-data:
  grafana-data: