apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: company
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: company
  namespaceSelector:
    matchNames:
      - jobapp
  targetLabels:
    - application
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 3s